src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 */
class Recipe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $preparation_time;

    /**
     * @ORM\Column(type="integer")
     */
    private $cooking_time;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="text")
     */
    private $steps;

    /**
     * @ORM\ManyToMany(targetEntity=User::class)
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=Quantity::class, mappedBy="recipe", cascade={"persist", "remove"})
     */
    private $quantities;

    /**
     * @ORM\OneToMany(targetEntity=FavoriteRecipes::class, mappedBy="recipe")
     */
    private $favoriteRecipes;

    /**
     * @ORM\OneToMany(targetEntity=Rate::class, mappedBy="recipe")
     */
    private $rates;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->quantities = new ArrayCollection();
        $this->favoriteRecipes = new ArrayCollection();
        $this->rates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparation_time;
    }

    public function setPreparationTime(int $preparation_time): self
    {
        $this->preparation_time = $preparation_time;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->cooking_time;
    }

    public function setCookingTime(int $cooking_time): self
    {
        $this->cooking_time = $cooking_time;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getSteps(): ?string
    {
        return $this->steps;
    }

    public function setSteps(string $steps): self
    {
        $this->steps = $steps;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection|Quantity[]
     */
    public function getQuantities(): Collection
    {
        return $this->quantities;
    }

    public function addQuantity(Quantity $quantity): self
    {
        if (!$this->quantities->contains($quantity)) {
            $this->quantities[] = $quantity;
            $quantity->setRecipe($this);
        }

        return $this;
    }

    public function removeQuantity(Quantity $quantity): self
    {
        if ($this->quantities->removeElement($quantity)) {
            // set the owning side to null (unless already changed)
            if ($quantity->getRecipe() === $this) {
                $quantity->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|FavoriteRecipes[]
     */
    public function getFavoriteRecipes(): Collection
    {
        return $this->favoriteRecipes;
    }

    public function addFavoriteRecipe(FavoriteRecipes $favoriteRecipe): self
    {
        if (!$this->favoriteRecipes->contains($favoriteRecipe)) {
            $this->favoriteRecipes[] = $favoriteRecipe;
            $favoriteRecipe->setRecipe($this);
        }

        return $this;
    }

    public function removeFavoriteRecipe(FavoriteRecipes $favoriteRecipe): self
    {
        if ($this->favoriteRecipes->removeElement($favoriteRecipe)) {
            // set the owning side to null (unless already changed)
            if ($favoriteRecipe->getRecipe() === $this) {
                $favoriteRecipe->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Rate[]
     */
    public function getRates(): Collection
    {
        return $this->rates;
    }

    public function addRate(Rate $rate): self
    {
        if (!$this->rates->contains($rate)) {
            $this->rates[] = $rate;
            $rate->setRecipe($this);
        }

        return $this;
    }

    public function removeRate(Rate $rate): self
    {
        if ($this->rates->removeElement($rate)) {
            // set the owning side to null (unless already changed)
            if ($rate->getRecipe() === $this) {
                $rate->setRecipe(null);
            }
        }

        return $this;
    }

}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Form\RecipeFormType;
use App\Entity\Recipe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class RecipeController extends AbstractController
{
    /**
     * @Route("/add-recipe", name="add_recipe")
     */
    public function addRecipe(Request $request): Response
    {
		$recipe = new Recipe();
        $form = $this->createForm(RecipeFormType::class, $recipe);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $entityManager = $this->getDoctrine()->getManager();
	        $entityManager->persist($recipe);
	        $entityManager->flush();
        }        

        return $this->render("recipe/recipe-form.html.twig", [
            "form_title" => "Add recipe",
            "form" => $form->createView(),
        ]);
    }

    /**
     * @Route("/recipes", name="recipes")
     */
    public function recipes()
    {
		$recipes = $this->getDoctrine()->getRepository(Recipe::class)->findAll();
        
        return $this->render("recipe/recipes.html.twig", [
            "recipes" => $recipes,
        ]);
    }

    /**
     * @Route("/recipe/{id}", name="recipe")
     */
    public function recipe(int $id): Response
    {
		$recipe = $this->getDoctrine()->getRepository(Recipe::class)->find($id);
       
        return $this->render("recipe/recipe.html.twig", [
            "recipe" => $recipe,
        ]);
    }

    /**
     * @Route("/modify-recipe/{id}", name="modify_recipe")
     */
    public function modifyRecipe(Request $request, int $id): Response
	{
	    $entityManager = $this->getDoctrine()->getManager();
	    $recipe = $entityManager->getRepository(Recipe::class)->find($id);
	    $form = $this->createForm(RecipeFormType::class, $recipe);
	    $form->handleRequest($request);
	    if($form->isSubmitted() && $form->isValid())
	    {
	        $entityManager->flush();
	    }
	    return $this->render("recipe/recipe-form.html.twig", [
	        "form_title" => "Edit recipe",
	        "form" => $form->createView(),
	    ]);
	}

	/**
     * @Route("/delete-recipe/{id}", name="delete_recipe")
     */
	public function deleteRecipe(int $id): Response
	{
	    $entityManager = $this->getDoctrine()->getManager();
	    $recipe = $entityManager->getRepository(Recipe::class)->find($id);
	    $entityManager->remove($recipe);
	    $entityManager->flush();
	    return $this->redirectToRoute("recipes");
	}
}

templates/recipe/recipe-form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecipeController!{% endblock %}

{% block body %}
	<style>
	    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
	    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
	</style>

	<h1>{{ form_title }}</h1>
	{{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.preparation_time) }}
        {{ form_row(form.cooking_time) }}
        {{ form_row(form.steps) }}
        {{ form_row(form.comments) }}

<ul class="ingredient-quantities {{ form.quantities | length > 0 ? '' : 'hidden'}}"
    data-index="{{ form.quantities|length > 0 ? form.quantities|last.vars.name + 1 : 0 }}"
    data-prototype="{{ form_widget(form.quantities.vars.prototype)|e('html_attr') }}"
>
    {% for ingredientQuantity in form.quantities %}
        <li>{{ form_row(ingredientQuantity.quantity) }}</li>
    {% endfor %}
</ul>
<button type="button" class="add-ingredient-quantities"
        data-collection-holder-class="ingredient-quantities"
        onClick="addToCollection('.ingredient-quantities')">
    Add an ingredient quantity
</button>

{{ form_end(form) }}


{% endblock %}

{% block javascripts %}
    <script>
        function addToCollection(which) {
            const collectionHolder = document.querySelector(which);
            const item = document.createElement('li');
            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/g,
                    collectionHolder.dataset.index
                );
            collectionHolder.classList.remove('hidden');
            collectionHolder.appendChild(item);
            collectionHolder.dataset.index++;
        }
    </script>
{% endblock %}

templates/recipe/recipe.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello RecipeController!{% endblock %}
{% block body %}
<h1>Recipe Page</h1>
<p>Name : {{ recipe.name }}</p>
<p>Preparation Time : {{ recipe.preparationTime }}</p>
<p>Cooking Time : {{ recipe.cookingTime }}</p>
<p>Steps : {{ recipe.steps }}</p>
<p>Comment : {{ recipe.comments }}</p>

<table>
   <h3>Ingredients</h3>
	<tr>
            <td>
                {% for ingredient in recipe.quantities %}
                    <li>{{ ingredient.quantity }} {{ ingredient.ingredient }}</li>
                {% endfor %}
            </td>
    </tr>
</table>

{% endblock %}

templates/recipe/recipes.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello RecipeController!{% endblock %}
{% block body %}
<h1>Recipes List</h1>
<p><a href="{{ path('add_recipe') }}">Add a recipe</a></p>
{% for recipe in recipes %}
    <table>
        <thead>
            <th>Name</th>
            <th>Preparation time</th>
            <th>Cooking time</th>
        </thead>
        <tbody>
            <td>{{ recipe.name }}</td>
            <td>{{ recipe.preparationTime }}</td>
            <td>{{ recipe.cookingTime }}</td>
        </tbody>
    </table>

    <td><a href="{{ path('recipe', {'id': recipe.id}) }}">{{ recipe.name }}</a></td>

    <table>
        <tbody>
            <td><a href="{{ path('modify_recipe', {'id': recipe.id}) }}">Edit</a></td>
        </tbody>
    </table>

    <table>
        <tbody>
            <td><a href="{{ path('delete_recipe', {'id': recipe.id}) }}">Delete</a></td>
        </tbody>
    </table>
{% endfor %}
{% endblock %}